export const ADD_TASK='ADD_TASK';
export const REMOVE_TASK='REMOVE_TASK';
export const TOGGLE_TASK='TOGGLE_TASK';
export const MARK_COMPLETE='MARK_COMPLETE';
export const MARK_INCOMPLETE='MARK_INCOMPLETE';
export const FILTER_TASK='FILTER_TASK';
export const MARK_ALL_COMPLETE='MARK_ALL_COMPLETE';
export const UPDATE_SEARCH_TERM='UPDATE_SEARCH_TERM';